#!/usr/bin/env python3

from argparse import ArgumentParser
import re

parser = ArgumentParser()

parser.add_argument('input')
parser.add_argument('output')

args = parser.parse_args()

intval = int(re.sub('[^\d]', '', args.input))
bytelen = (intval.bit_length() + 7) // 8

with open(args.output,'bw') as fd:
  fd.write(intval.to_bytes(bytelen, 'big'))

